INSERT INTO operacion.tipo_campo (nombre, descripcion, usuario_creacion) VALUES
    ('text', 'Campo de texto corto para nombres o respuestas breves', 'system'),
    ('textarea', 'Campo de texto multilínea para descripciones o comentarios', 'system'),
    ('number', 'Campo para ingresar valores numéricos', 'system'),
    ('email', 'Campo para ingresar correos electrónicos con validación', 'system'),
    ('tel', 'Campo para números telefónicos', 'system'),
    ('url', 'Campo para direcciones web', 'system'),
    ('password', 'Campo que oculta los caracteres ingresados', 'system'),
    ('date', 'Campo para seleccionar una fecha', 'system'),
    ('time', 'Campo para seleccionar una hora', 'system'),
    ('datetime-local', 'Campo para seleccionar fecha y hora', 'system'),
    ('select', 'Lista desplegable para seleccionar una opción', 'system'),
    ('radio', 'Grupo de opciones donde solo se puede elegir una', 'system'),
    ('checkbox', 'Casillas que permiten seleccionar una o varias opciones', 'system'),
    ('file', 'Campo para subir archivos', 'system'),
    ('range', 'Selector deslizante para elegir un valor dentro de un rango', 'system'),
    ('color', 'Selector visual de color', 'system'),
    ('hidden', 'Campo oculto no visible para el usuario', 'system');

INSERT INTO operacion.tipo_validacion (nombre, descripcion, usuario_creacion) VALUES
    ('required','El campo es obligatorio','system'),
    ('min_length','Longitud mínima de texto','system'),
    ('max_length','Longitud máxima de texto','system'),
    ('regex','Validación por expresión regular','system'),
    ('min_value','Valor numérico mínimo','system'),
    ('max_value','Valor numérico máximo','system'),
    ('greater_than','Mayor que valor','system'),
    ('greater_or_equal','Mayor o igual','system'),
    ('less_than','Menor que valor','system'),
    ('less_or_equal','Menor o igual','system'),
    ('min_date','Fecha mínima permitida','system'),
    ('max_date','Fecha máxima permitida','system'),
    ('after_date','Debe ser posterior a una fecha','system'),
    ('before_date','Debe ser anterior a una fecha','system'),
    ('email_format','Formato válido de email','system'),
    ('url_format','Formato válido de URL','system'),
    ('phone_format','Formato válido de teléfono','system'),
    ('integer_only','Solo números enteros','system'),
    ('decimal_places','Cantidad de decimales permitidos','system'),
    ('min_selected','Mínimo de opciones seleccionadas','system'),
    ('max_selected','Máximo de opciones seleccionadas','system'),
    ('max_file_size','Tamaño máximo de archivo','system'),
    ('allowed_extensions','Extensiones permitidas','system'),
    ('greater_than_field','Mayor que otro campo','system'),
    ('less_than_field','Menor que otro campo','system'),
    ('equals_field','Igual a otro campo','system'),
    ('not_equals_field','Diferente de otro campo','system');